# This is a basic workflow to help you get started with Actions

name: Update Data

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-data:
    name: Download and update data
    runs-on: "macos-latest"
    steps:
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: 'release'
      - name: install packages
        run: |                  
          install.packages('dplyr')
          install.packages('remotes')
          remotes::install_github("nevrome/covid19germany")        
        shell: Rscript {0} 
      - name: Checkout repo
        uses: actions/checkout@v2       
      - name: "Download data"
        run: |
          source('R/job.R')
        shell: Rscript {0}
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "update data"
          git push 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
